export const WORKERS_REQUEST = 'WORKERS_REQUEST';
export const WORKERS_SUCCESS = 'WORKERS_SUCCESS';
export const WORKERS_FAILURE = 'WORKERS_FAILURE';

export const WORKER_EDIT_REQUEST = 'WORKER_EDIT_REQUEST';
export const WORKER_EDIT_SUCCESS = 'WORKER_EDIT_SUCCESS';
export const WORKER_EDIT_FAILURE = 'WORKER_EDIT_FAILURE';

export const WORKER_REMOVE_REQUEST = 'WORKER_REMOVE_REQUEST';
export const WORKER_REMOVE_SUCCESS = 'WORKER_REMOVE_SUCCESS';
export const WORKER_REMOVE_FAILURE = 'WORKER_REMOVE_FAILURE';
